# Generated by Django 5.2.5 on 2026-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="active_backlogs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
