# Generated by Django 5.2.5 on 2026-02-28 14:44

import api.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
    ]
