# Generated by Django 5.2.5 on 2026-03-19 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_application_status_history(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    ApplicationStatusHistory = apps.get_model("applications", "ApplicationStatusHistory")

    history_rows = []
    for application in Application.objects.all():
        history_rows.append(
            ApplicationStatusHistory(
                application_id=application.id,
                previous_status_id=None,
                new_status_id=application.status_id,
                remarks="Backfilled initial status history.",
                changed_by_id=None,
                changed_at=application.application_date,
            )
        )

    if history_rows:
        ApplicationStatusHistory.objects.bulk_create(history_rows)


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_applicationstatus_refactor_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="applications.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history_entries",
                        to="applications.applicationstatus",
                    ),
                ),
                (
                    "previous_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="applications.applicationstatus",
                    ),
                ),
            ],
            options={
                "db_table": "applications_status_history",
                "ordering": ["-changed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["application", "changed_at"],
                        name="application_applica_4a8d90_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_application_status_history,
            migrations.RunPython.noop,
        ),
    ]
