# Generated by Django 5.2.5 on 2026-03-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("placements", "0003_jobrequiredskill_alter_placement_required_skills"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "placement",
                    models.ForeignKey(
                        db_column="placement_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarked_by",
                        to="placements.placement",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "bookmarks_bookmark",
                "unique_together": {("student", "placement")},
            },
        ),
    ]
