# Generated by Django 5.2.5 on 2026-02-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "jobs_skill"},
        ),
        migrations.AddField(
            model_name="placement",
            name="no_of_applicants",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="placement",
            name="no_of_positions",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="placement",
            name="required_skills",
            field=models.ManyToManyField(
                db_table="jobs_job_required_skills",
                related_name="placements",
                to="placements.skill",
            ),
        ),
    ]
