# Generated by Django 5.2.5 on 2026-03-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0002_skill_placement_no_of_applicants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRequiredSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        db_column="job_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="placements.placement",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        db_column="skill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="placements.skill",
                    ),
                ),
            ],
            options={
                "db_table": "jobs_job_required_skills",
                "managed": False,
                "unique_together": {("placement", "skill")},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="placement",
                    name="required_skills",
                    field=models.ManyToManyField(
                        related_name="placements",
                        through="placements.JobRequiredSkill",
                        to="placements.skill",
                    ),
                ),
            ],
        ),
    ]
