# Generated by Django 5.2.5 on 2026-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0003_jobrequiredskill_alter_placement_required_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="placement",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
