# Generated by Django 5.2.5 on 2026-03-19 14:30

import django.db.models.deletion
from django.db import migrations, models


def backfill_eligibility_criteria(apps, schema_editor):
    Placement = apps.get_model("placements", "Placement")
    EligibilityCriteria = apps.get_model("placements", "EligibilityCriteria")

    existing_criteria_ids = set(
        EligibilityCriteria.objects.values_list("placement_id", flat=True)
    )
    criteria_to_create = [
        EligibilityCriteria(
            placement_id=placement.id,
            min_cgpa=placement.eligibility_cgpa,
        )
        for placement in Placement.objects.all()
        if placement.id not in existing_criteria_ids
    ]
    EligibilityCriteria.objects.bulk_create(criteria_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("placements", "0004_placement_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_cgpa", models.FloatField()),
                (
                    "max_backlogs",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("requires_resume", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "placement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_criteria",
                        to="placements.placement",
                    ),
                ),
            ],
            options={
                "db_table": "jobs_eligibility_criteria",
            },
        ),
        migrations.CreateModel(
            name="EligibleDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=50)),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_departments",
                        to="placements.eligibilitycriteria",
                    ),
                ),
            ],
            options={
                "db_table": "jobs_eligible_departments",
            },
        ),
        migrations.AddConstraint(
            model_name="eligibilitycriteria",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_cgpa__gte", 0), ("min_cgpa__lte", 10)),
                name="eligibility_min_cgpa_range",
            ),
        ),
        migrations.AddIndex(
            model_name="eligibledepartment",
            index=models.Index(
                fields=["department_name"], name="jobs_eligib_departm_336533_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eligibledepartment",
            unique_together={("criteria", "department_name")},
        ),
        migrations.RunPython(backfill_eligibility_criteria, migrations.RunPython.noop),
    ]
