# Generated by Django 5.2.5 on 2026-03-19 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0003_applicationstatushistory"),
        ("placements", "0005_eligibilitycriteria_eligibledepartment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("application_submitted", "Application Submitted"),
                            (
                                "application_status_changed",
                                "Application Status Changed",
                            ),
                            ("job_created", "Job Created"),
                            ("job_updated", "Job Updated"),
                            ("eligibility_updated", "Eligibility Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="applications.application",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="placements.placement",
                    ),
                ),
            ],
            options={
                "db_table": "activitylog_entry",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="activitylog_action__49a3a8_idx",
                    ),
                    models.Index(
                        fields=["placement", "created_at"],
                        name="activitylog_placeme_e77068_idx",
                    ),
                    models.Index(
                        fields=["application", "created_at"],
                        name="activitylog_applica_478743_idx",
                    ),
                ],
            },
        ),
    ]
