# Generated by Django 5.2.5 on 2026-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
